export const types = {
 LOGIN_NETWORK_ERROR: 'LOGIN_NETWORK_ERROR',
 LOGIN_ERROR: 'EMAIL_ERROR',
 LOGIN: 'EMAIL_SIGNUP',
 LOGIN_LOADING: 'SIGNUP_LOADING',
 SET_LOGGED_IN: 'SET_LOGGED_IN',
 LOGOUT: 'LOGOUT',
 
};
